### ISSUE TITLE
Audio duration is wrong in safari

### ISSUE THREAD

**Issue by skdev24** [nico-martin/yt-audio#6]
Hey,

When I play any youtube video in safari there's extra time gets added like 6:00 min audio on youtube here it shows 13:00 min.

<img width="529" alt="Screenshot 2020-01-16 at 8 40 34 PM" src="https://user-images.githubusercontent.com/16745006/72536722-cc326900-38a0-11ea-8660-7556aa85d3ba.png">

I believe the issue is in the link you generate after adding the youtube id from server.

Video link: https://www.youtube.com/watch?v=_tNU6dpjIyM

**Comment by nico-martin** [comment]
Hi @skdev24,

Does this problem still exists? Or have you been able  to solve it?

Kind regards,
Nico

**Comment by skdev24** [comment]
@nico-martin The issue is with the url that is generated by "ytdl-core" the url format you using in the backend, also one more thing please check the access of some video is denied like none of Eminem video you can play, I'm also working on something but I'm building iOS and Android app, and I went to directly use the "ytdl-core" because your api doesn't have access to some videos, for above issue I believe need to check different format for iOS.
